module.exports=[
  {hostname: "eyelevel.ai", pathname: "/okcool", search: "?test=okk&ab=cd"},
  {hostname: "www.eyelevel.ai", pathname: "/okcool", search: "?asd=sa&test=okk"},
  {hostname: "golang.org", pathname: "/okcool", search: "?asd=sa"},
  {hostname: "eyelevel.ai", pathname: ""},
  {hostname: "eyelevel.ai", pathname: "/okcool/man"},
  {hostname: "eyelevel.ai", pathname: "/okcool/test/man"},
  {hostname: "eyelevel.ai", pathname: "/test34"},
  {hostname: "eyelevel.ai", pathname: "test/ok"},
  {hostname: "eyelevel.ai", pathname: "okcool/test"},
  {hostname: "eyelevel.ai", pathname: "okcool/test2/ass"},
  {hostname: "www.eyelevel.ai", pathname: "okcool/test"},
  {hostname: "www.eyelevel.ai", pathname: "/ass/okcool/test"},
  {hostname: "golang.org", pathname: "okcool/test2"},
  {hostname: "golang.org", pathname: "/assokcool/test"},
  {hostname: "golang.org", pathname: "/okcool/ass/test"},
  {hostname: "resources.eyelevel.ai", pathname: "/ab/ok"},
  {hostname: "www.eyelevel.ai", pathname: "/ab/ok"},
  {hostname: "eyelevel.ai", pathname: "ab/ok"},
  {hostname: "eyelevel.ai", pathname: "abb"},
  {hostname: "eyelevel.ai", pathname: "/abb"},
  {hostname: "eyelevel.ai", pathname: "/ok/ab"},
  {hostname: "eyelevel.ai", pathname: "/ab/ok/cd"},
  {hostname: "eyelevel.ai", pathname: "/abcd"},
  {hostname: "eyelevel.ai", pathname: "/cd/ab"},
  {hostname: "golang.org", pathname: "/test55/playground/test25"},
  {hostname: "golang.org", pathname: "/playgrounds/are/fun"},
  {hostname: "golang.org", pathname: "/playground", search: "?another=one&ok=true"},
];